export enum LEAF_BE_TAGS {
  HEADING = 'HEADING',
  TEXT = 'TEXT',
  // CODE = 'CODE',
  // IMAGE = 'IMAGE',
  // LINK = 'LINK',
}

export enum LISTABLE_BE_TAGS {
  BULLETED_LIST = 'BULLETED_LIST',
  NUMBERED_LIST = 'NUMBERED_LIST',
  TOGGLE_LIST = 'TOGGLE_LIST',
  TOGGLE_HEADING_LIST = 'TOGGLE_HEADING_LIST',
}

export enum RECURSIVE_BE_TAGS {
  ROOT = 'ROOT',
  CONTAINER_ROW = 'CONTAINER_ROW',
  CONTAINER_COLUMN = 'CONTAINER_COLUMN',

  BULLETED_LIST = LISTABLE_BE_TAGS.BULLETED_LIST,
  NUMBERED_LIST = LISTABLE_BE_TAGS.NUMBERED_LIST,
  TOGGLE_LIST = LISTABLE_BE_TAGS.TOGGLE_LIST,
  TOGGLE_HEADING_LIST = LISTABLE_BE_TAGS.TOGGLE_HEADING_LIST,
}

export const APP_ENUMS = {
  BE_TAGS: { ...LEAF_BE_TAGS, ...RECURSIVE_BE_TAGS },
  LEAF_BE_TAGS: LEAF_BE_TAGS,
  RECURSIVE_BE_TAGS: RECURSIVE_BE_TAGS,
  LISTABLE_BE_TAGS: LISTABLE_BE_TAGS,
};
